### PR TITLE
Update Parser.d

### PR DESCRIPTION
**Pull request by IkeVoodoo**
Fixed some code

### CODE REVIEW

**Comment by tokito7391** [comment]
why d

**Comment by IkeVoodoo** [comment]
cause he is using D

**Comment by tokito7391** [comment]
ok

**Comment by berkerdemoglu** [comment]
I think developers should have the option of not specifying the access modifier and it can either be inferred as `package-private` like Java or just straight up `public`. What do you say?

**Comment by MiyukiNozomi** [comment]
> why d

D is memory-safe, has some java-like stuff.
and its bettwen hell and heaven.

**Comment by MiyukiNozomi** [comment]
> Fixed some code

 nice change, at the time that i wrote that parser i was discurssing with some people in discord, so i didn't saw what i was writing XD, sadly, i broke this parser into 3 other files for a big update, so. i will implement your changes later.

thanks <3

**Pull request closed without merging**
